# Generated by Django 4.0.6 on 2022-07-27 10:37

from django.conf import settings
from django.db import migrations, models
import projects.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя проекта')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL_project')),
                ('priority', models.PositiveIntegerField(validators=[projects.validators.priority], verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('created', 'created'), ('launched', 'launched'), ('stopped', 'stopped')], default='created', max_length=20)),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('performer', models.ManyToManyField(blank=True, null=True, related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители проекта')),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['creation_time'],
            },
        ),
    ]
